<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <script src="js/jquery-3.3.1.slim.min.js"></script>
    <!-- <script src="js/jquery-migrate-1.2.1.min.js"></script> -->
    <script src="js/tether.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/sweetalert.min.js"></script>
    <script src="js/waiter.js?v=1.0.39" type="text/javascript"></script><!--Arquivo java script com intruções para o HTML-->
    <script src="js/jquery.datetimepicker.full.js"></script><!--Pluguin Jquery para data e hora https://plugins.jquery.com/datetimepicker/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
   
    
</head>
<body>

    <h1>Layout 1</h1>
    <div>
    <span class="border border-primary"></span>
    </div>
    <?= $this->content() ?>
</body>
</html>